server:
  port: 8761
eureka:
  client:
    service-url:
    # 注册的地址
        defaultZone: http://localhost:8761/eureka/
    # 是否注册eureka自己
    register-with-eureka: true
spring:
  application:
    name: eureka